language: node_js
node_js:
  - "14"
  - "15"
  - "lts/*"
  - "node"

before_install:
  - npm i -g npm@7

install:
  - gem install coveralls-lcov
  - npm install

after_success:
  - npm run coverage && coveralls-lcov coverage/lcov.info