language: node_js
node_js:
  - "14"
  - "15"
  - "lts/*"
  - "node"

before_install:
  - gem install coveralls-lcov
  - npm i -g npm@7
  - npm i -g codecov

after_success:
  - npm run coverage && codecov && coveralls-lcov coverage/lcov.info